DISPLAY_HEIGHT = 24
DISPLAY_WIDTH = 80

PONG_WIDTH = 80
PONG_HEIGHT = 24

LEFT_BAT_I2C_ADDRESS = 0x3a

RIGHT_BAT_CMD_CODE = 0x40
RIGHT_BAT_I2C_ADDRESS = 0x21

BAT_BUTTONS_I2C_ADDRESS = 0x38
BAT_BUTTONS_INTERRUPT_PIN = 10

LEFT_BAT_TOP_BUTTON = 0x02
LEFT_BAT_BOT_BUTTON = 0x01

RIGHT_BAT_TOP_BUTTON = 0x08
RIGHT_BAT_BOT_BUTTON = 0x04

NUMBER_OF_SIZE_INCREASES = 2
SIZE_INCREASE_TIME = 15
INCREASE_FACTOR = 2

BALL_LED_I2C_ADDRESS = 0x39

CPLD_MAX_RANGE = 120
CPLD_VOLTAGE_AT_MAX = 3.1

SEVEN_SEG_DISPLAY_ADDR = 0x3c
